global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  - job_name: 'go-app'
    static_configs:
      - targets: ['go-app:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 5s

  - job_name: 'blackbox'
    static_configs:
      - targets: ['blackbox_exporter:9115']
    scrape_interval: 5s

  # Blackbox probes for internal application health endpoints
  - job_name: 'blackbox_http_internal'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://go-app:8080/healthz
        - http://go-app:8080/readyz
        - http://go-app:8080/api/v1/ping
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: probe_type
        replacement: internal

  # Blackbox probes for external targets
  # To add more targets, add them to the targets list below
  # These correspond to BLACKBOX_EXTERNAL_TARGET_* environment variables
  - job_name: 'blackbox_http_external'
    metrics_path: /probe
    params:
      module: [http_external]
    static_configs:
      - targets:
        - https://httpbin.org/status/200  # BLACKBOX_EXTERNAL_TARGET_1
        - https://example.com             # BLACKBOX_EXTERNAL_TARGET_2
        - https://google.com              # BLACKBOX_EXTERNAL_TARGET_3
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
      - target_label: probe_type
        replacement: external